const fonts = {
  RalewayBlack: 'Raleway-Black',
  RalewayBlackItalic: 'Raleway-BlackItalic',
  RalewayBold: 'Raleway-Bold',
  RalewayBoldItalic: 'Raleway-BoldItalic',
  RalewayExtraBold: 'Raleway-ExtraBold',
  RalewayExtraBoldItalic: 'Raleway-ExtaBoldItalic',
  RalewayExtraLight: 'Raleway-ExtraLight',
  RalewayExtraLightItalic: 'Raleway-ExtraLightItalic',
  RalewayItalic: 'Raleway-Italic',
  RalewayLight: 'Raleway-Light',
  RalewayLightItalic: 'Raleway-LightItalic',
  RalewayMedium: 'Raleway-Medium',
  RalewayMediumItalic: 'Raleway-MediumItalic',
  RalewayRegular: 'Raleway-Regular',
  RalewaySemiBold: 'Raleway-SemiBold',
  RalewaySemiBoldItalic: 'Raleway-SemiBoldItalic',
  RalewayThin: 'Raleway-Thin',
  RalewayThinItalic: 'Raleway-ThinItalic',
  PoppinsBlack: 'Poppins-Black',
  PoppinsLight: 'Poppins-Light',
  PoppinsMedium: 'Poppins-Medium',
  PoppinsRegular: 'Poppins-Regular',
};

export default fonts;
