export const REGISTER_ENABLE_LOADER = 'REGISTER_ENABLE_LOADER';
export const REGISTER_DISABLE_LOADER = 'REGISTER_DISABLE_LOADER';
export const REGISTRATION_ERROR = "REGISTRATION_ERROR";
export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";

